Go SDK: Ensure tunnels.go is updated when there's a change to the go sdk folder

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -32,3 +32,15 @@ jobs:
         go-version: 1.17
     - name: Test
       run: cd go/tunnels && go test -short -v ./...
+
+  check_package_version:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v2
+    - name: Check Go SDK package version updated
+      run: |
+        BASE_SHA=$(jq -r '.pull_request.base.sha' "$GITHUB_EVENT_PATH")
+        if git diff --name-only $BASE_SHA HEAD | grep '^go/' && ! git diff --name-only $BASE_SHA HEAD | grep '^go/tunnels/tunnels.go'; then
+          echo "Error: Go SDK directory was changed without updating tunnels.go. PackageVersion in tunnels.go needs to be manually updated."
+          exit 1
+        fi
