t

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -46,12 +46,14 @@ jobs:
         test -d $SDK_DIR && test -f $FILE_WITH_PKG_VER
         BASE_SHA=$(jq -r '.pull_request.base.sha' "$GITHUB_EVENT_PATH")
         # If go sdk dir updated, package version file updated and "PackageVersion" line updated, success; else error.
-        if git diff --name-only $BASE_SHA HEAD | grep '^$SDK_DIR' && ! git diff --name-only $BASE_SHA HEAD | grep '^$FILE_WITH_PKG_VER' && git diff $BASE_SHA HEAD -- $FILE_WITH_PKG_VER | grep -q "PackageVersion"; then
-          echo "Success: Package version was updated."
-          exit 0
-        else
-          echo "Error: An error occurred. Has "PackageVersion" in $FILE_WITH_PKG_VER been updated?"
-          git diff --name-only $BASE_SHA HEAD
-          git diff $BASE_SHA HEAD -- $FILE_WITH_PKG_VER
-          exit 1
+        if git diff --name-only $BASE_SHA HEAD | grep '^$SDK_DIR'; then
+          if git diff --name-only $BASE_SHA HEAD | grep '^$FILE_WITH_PKG_VER' && git diff $BASE_SHA HEAD -- $FILE_WITH_PKG_VER | grep -q "PackageVersion"; then
+            echo "Success: Package version was updated."
+            exit 0
+          else
+            echo "Error: An error occurred. Has "PackageVersion" in $FILE_WITH_PKG_VER been updated?"
+            git diff --name-only $BASE_SHA HEAD
+            git diff $BASE_SHA HEAD -- $FILE_WITH_PKG_VER
+            exit 1
+          fi
         fi
